services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./life_game:/usr/src/app:cached
    command: poetry run jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888
    ports:
      - 8888:8888
    tty: true